# 使用 Python 官方映像檔作為基底
FROM python:3.10.12-slim

# setup workfile
WORKDIR /app
COPY . .

# RUN apt-get install build-dep python-psycopg2

# install python packages
RUN pip install --upgrade pip
RUN pip install Django
RUN pip install psycopg2-binary
RUN pip install djangorestframework
RUN pip install markdown
RUN pip install django-filter
RUN pip install drf-yasg
RUN pip install python-dotenv
RUN pip install uvicorn
RUN pip install bson

# RUN python manage.py migrate

CMD ["python", "main.py"]